import 'package:flutter/material.dart';

import 'Entities/OutletsListEntity.dart';

String localhost = "http://192.168.0.118:8000";

List<Color> colorIndex = [
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.pink,
  Colors.purple,
  Colors.deepOrange,
  Colors.brown,
  Colors.teal,
  Colors.lightGreen,
  Colors.deepPurple,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.lightGreenAccent,
  Colors.tealAccent,
  Colors.deepPurpleAccent,
  Colors.lightBlueAccent,
  Colors.redAccent,
  Colors.deepOrangeAccent,
  Colors.cyan,
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.pink,
  Colors.purple,
  Colors.deepOrange,
  Colors.brown,
  Colors.teal,
  Colors.lightGreen,
  Colors.deepPurple,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.lightGreenAccent,
  Colors.tealAccent,
  Colors.deepPurpleAccent,
  Colors.lightBlueAccent,
  Colors.redAccent,
  Colors.deepOrangeAccent,
  Colors.cyan,
  Colors.green,
  Colors.yellow,
  Colors.orange,
  Colors.pink,
  Colors.purple,
  Colors.deepOrange,
  Colors.brown,
  Colors.teal,
  Colors.lightGreen,
  Colors.deepPurple,
  Colors.indigo,
  Colors.indigoAccent,
  Colors.lightGreenAccent,
  Colors.tealAccent,
  Colors.deepPurpleAccent,
  Colors.lightBlueAccent,
  Colors.redAccent,
  Colors.deepOrangeAccent,
  Colors.cyan,
];

String logo = "assets/logo.svg";
String logo1 = "assets/logo.png";
